name: Docker

env:
  DOCKER_IMAGE_NAME: keycape
  DOCKER_USERNAME: baaka
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker build $GITHUB_WORKSPACE -t $DOCKER_USERNAME/$DOCKER_IMAGE_NAME
      - name: Login to Docker Hub
        run: docker login --username=$DOCKER_USERNAME --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        run: docker push $DOCKER_USERNAME/$DOCKER_IMAGE_NAME
