name: Netlify
on:
  push:
    branches: [ master ]
    paths:
      - "website/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run a one-line script
      run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
